"""Added average_week_fulfillment_percentage column to organizations

Revision ID: 1e7ea252a79b
Revises: 6523a0a9e606
Create Date: 2024-06-30 17:13:13.707450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e7ea252a79b'
down_revision: Union[str, None] = '6523a0a9e606'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('average_week_fulfillment_percentage', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'average_week_fulfillment_percentage')
    # ### end Alembic commands ###
