"""Added column connected to organizations

Revision ID: 386ed5e14e1e
Revises: 
Create Date: 2024-08-01 15:09:35.023429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '386ed5e14e1e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('founder', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('the_main_state_registration_number', sa.BigInteger(), nullable=True),
    sa.Column('screen_name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('sphere_1', sa.String(), nullable=True),
    sa.Column('sphere_2', sa.String(), nullable=True),
    sa.Column('sphere_3', sa.String(), nullable=True),
    sa.Column('activity', sa.String(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('has_avatar', sa.Boolean(), nullable=False),
    sa.Column('has_cover', sa.Boolean(), nullable=False),
    sa.Column('has_description', sa.Boolean(), nullable=False),
    sa.Column('has_gos_badge', sa.Boolean(), nullable=False),
    sa.Column('has_widget', sa.Boolean(), nullable=True),
    sa.Column('widget_count', sa.Integer(), nullable=True),
    sa.Column('members_count', sa.Integer(), nullable=False),
    sa.Column('connected', sa.Boolean(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('site', sa.String(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('posts', sa.Integer(), nullable=False),
    sa.Column('posts_1d', sa.Integer(), nullable=False),
    sa.Column('posts_7d', sa.Integer(), nullable=False),
    sa.Column('posts_30d', sa.Integer(), nullable=False),
    sa.Column('average_week_fulfillment_percentage', sa.Integer(), nullable=False),
    sa.Column('average_fulfillment_percentage', sa.Integer(), nullable=False),
    sa.Column('weekly_audience_reach', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id')
    )
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statistic',
    sa.Column('date_id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('date_added', sa.Date(), nullable=False),
    sa.Column('fulfillment_percentage', sa.Integer(), nullable=False),
    sa.Column('activity', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('date_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statistic')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
