"""Added average_fulfillment_percentage default value column to Organizations

Revision ID: 4c1278cdfb6b
Revises: 5b8401b58f48
Create Date: 2024-06-18 21:49:24.673983

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4c1278cdfb6b"
down_revision: Union[str, None] = "5b8401b58f48"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
