"""Added Optional column connected to organizations

Revision ID: 57c340c6cc72
Revises: 386ed5e14e1e
Create Date: 2024-08-01 15:13:19.484109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57c340c6cc72'
down_revision: Union[str, None] = '386ed5e14e1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organizations', 'connected',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organizations', 'connected',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
