"""Relationships update

Revision ID: 7e1348618ca0
Revises: 7f8d8f4fd2b3
Create Date: 2024-05-19 15:51:52.549647

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7e1348618ca0"
down_revision: Union[str, None] = "7f8d8f4fd2b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("account", sa.Column("organization_id", sa.Integer(), nullable=False))
    op.drop_constraint("account_channel_id_fkey", "account", type_="foreignkey")
    op.create_foreign_key(None, "account", "organizations", ["organization_id"], ["id"])
    op.drop_column("account", "channel_id")
    op.drop_constraint("organizations_channel_id_key", "organizations", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "organizations_channel_id_key", "organizations", ["channel_id"]
    )
    op.add_column(
        "account",
        sa.Column("channel_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "account", type_="foreignkey")
    op.create_foreign_key(
        "account_channel_id_fkey",
        "account",
        "organizations",
        ["channel_id"],
        ["channel_id"],
    )
    op.drop_column("account", "organization_id")
    # ### end Alembic commands ###
