"""Changed channel_idtype to int

Revision ID: 83075d40d575
Revises: 
Create Date: 2024-04-11 21:00:03.637676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83075d40d575'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('founder', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('the_main_state_registration_number', sa.BigInteger(), nullable=True),
    sa.Column('sphere_1', sa.String(), nullable=True),
    sa.Column('sphere_2', sa.String(), nullable=True),
    sa.Column('sphere_3', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('connected', sa.String(), nullable=True),
    sa.Column('state_mark', sa.Boolean(), nullable=True),
    sa.Column('decoration', sa.String(), nullable=True),
    sa.Column('widgets', sa.String(), nullable=True),
    sa.Column('activity', sa.String(), nullable=True),
    sa.Column('followers', sa.String(), nullable=True),
    sa.Column('weekly_audience', sa.String(), nullable=True),
    sa.Column('average_publication_coverage', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('organizations')
    # ### end Alembic commands ###
