"""Added level_1, level_2, level_3 and organizations tables

Revision ID: 9bd692aea873
Revises: 1711dc0829f8
Create Date: 2024-04-08 19:28:24.565804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bd692aea873'
down_revision: Union[str, None] = '1711dc0829f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('level_1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization', sa.String(), nullable=False),
    sa.Column('sphere', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('connected', sa.Boolean(), nullable=False),
    sa.Column('state_mark', sa.Boolean(), nullable=False),
    sa.Column('decoration', sa.Boolean(), nullable=False),
    sa.Column('widgets', sa.Integer(), nullable=False),
    sa.Column('activity', sa.Integer(), nullable=False),
    sa.Column('followers', sa.Integer(), nullable=False),
    sa.Column('weekly_audience', sa.Integer(), nullable=False),
    sa.Column('average_publication_coverage', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('level_2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization', sa.String(), nullable=False),
    sa.Column('sphere', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('connected', sa.Boolean(), nullable=False),
    sa.Column('state_mark', sa.Boolean(), nullable=False),
    sa.Column('decoration', sa.Boolean(), nullable=False),
    sa.Column('widgets', sa.Integer(), nullable=False),
    sa.Column('activity', sa.Integer(), nullable=False),
    sa.Column('followers', sa.Integer(), nullable=False),
    sa.Column('weekly_audience', sa.Integer(), nullable=False),
    sa.Column('average_publication_coverage', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('level_3',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('founder', sa.String(), nullable=False),
    sa.Column('organization', sa.String(), nullable=False),
    sa.Column('sphere', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('connected', sa.Boolean(), nullable=False),
    sa.Column('state_mark', sa.Boolean(), nullable=False),
    sa.Column('decoration', sa.Boolean(), nullable=False),
    sa.Column('widgets', sa.Integer(), nullable=False),
    sa.Column('activity', sa.Integer(), nullable=False),
    sa.Column('followers', sa.Integer(), nullable=False),
    sa.Column('weekly_audience', sa.Integer(), nullable=False),
    sa.Column('average_publication_coverage', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organizations')
    op.drop_table('level_3')
    op.drop_table('level_2')
    op.drop_table('level_1')
    # ### end Alembic commands ###
