"""Added level column

Revision ID: 9ff4933ce435
Revises: c256f3ffdb4c
Create Date: 2024-04-08 21:06:30.914458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ff4933ce435'
down_revision: Union[str, None] = 'c256f3ffdb4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('level', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'level')
    # ### end Alembic commands ###
