"""Added views_7d column to organizations

Revision ID: be90c5f08b60
Revises: 1e7ea252a79b
Create Date: 2024-07-03 18:05:49.721725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be90c5f08b60'
down_revision: Union[str, None] = '1e7ea252a79b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('views_7d', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'views_7d')
    # ### end Alembic commands ###
