"""Added account, statistic table

Revision ID: dc7e94442541
Revises: 83075d40d575
Create Date: 2024-05-04 17:51:48.214582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc7e94442541'
down_revision: Union[str, None] = '83075d40d575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('screen_name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('activity', sa.String(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('has_avatar', sa.Boolean(), nullable=False),
    sa.Column('has_cover', sa.Boolean(), nullable=False),
    sa.Column('has_description', sa.Boolean(), nullable=False),
    sa.Column('has_gos_badge', sa.Boolean(), nullable=False),
    sa.Column('has_widget', sa.Boolean(), nullable=False),
    sa.Column('widget_count', sa.Integer(), nullable=False),
    sa.Column('members_count', sa.Integer(), nullable=False),
    sa.Column('site', sa.String(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('posts', sa.Integer(), nullable=False),
    sa.Column('posts_1d', sa.Integer(), nullable=False),
    sa.Column('posts_7d', sa.Integer(), nullable=False),
    sa.Column('posts_30d', sa.Integer(), nullable=False),
    sa.Column('post_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statistic',
    sa.Column('date_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('members_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('date_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statistic')
    op.drop_table('account')
    # ### end Alembic commands ###
