"""Added members_count column to organizations

Revision ID: f00ebf09eaaa
Revises: 9db0e37a7dc7
Create Date: 2024-08-12 12:57:03.520507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f00ebf09eaaa'
down_revision: Union[str, None] = '9db0e37a7dc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('members_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'members_count')
    # ### end Alembic commands ###
