"""Added index for column name in organizations 2

Revision ID: f5250c1b3423
Revises: 6f02798e6810
Create Date: 2024-07-14 18:37:31.133249

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f5250c1b3423"
down_revision: Union[str, None] = "6f02798e6810"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
