"""Changed from sphere to founder column in users table

Revision ID: fb7e68f8b917
Revises: 6d2870489640
Create Date: 2024-08-30 11:33:27.229050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb7e68f8b917'
down_revision: Union[str, None] = '6d2870489640'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('founder', sa.String(), nullable=True))
    op.drop_column('users', 'sphere')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sphere', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'founder')
    # ### end Alembic commands ###
