"""Changed foreign key in statistic table

Revision ID: fccd361b8e03
Revises: 
Create Date: 2024-05-10 00:33:33.417738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fccd361b8e03'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('screen_name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('activity', sa.String(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('has_avatar', sa.Boolean(), nullable=False),
    sa.Column('has_cover', sa.Boolean(), nullable=False),
    sa.Column('has_description', sa.Boolean(), nullable=False),
    sa.Column('has_gos_badge', sa.Boolean(), nullable=False),
    sa.Column('has_widget', sa.Boolean(), nullable=False),
    sa.Column('widget_count', sa.Integer(), nullable=False),
    sa.Column('members_count', sa.Integer(), nullable=False),
    sa.Column('site', sa.String(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('posts', sa.Integer(), nullable=False),
    sa.Column('posts_1d', sa.Integer(), nullable=False),
    sa.Column('posts_7d', sa.Integer(), nullable=False),
    sa.Column('posts_30d', sa.Integer(), nullable=False),
    sa.Column('post_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('founder', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('the_main_state_registration_number', sa.BigInteger(), nullable=True),
    sa.Column('sphere_1', sa.String(), nullable=True),
    sa.Column('sphere_2', sa.String(), nullable=True),
    sa.Column('sphere_3', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('connected', sa.String(), nullable=True),
    sa.Column('state_mark', sa.Boolean(), nullable=True),
    sa.Column('decoration', sa.String(), nullable=True),
    sa.Column('widgets', sa.String(), nullable=True),
    sa.Column('activity', sa.String(), nullable=True),
    sa.Column('followers', sa.String(), nullable=True),
    sa.Column('weekly_audience', sa.String(), nullable=True),
    sa.Column('average_publication_coverage', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statistic',
    sa.Column('date_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('members_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('date_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statistic')
    op.drop_table('users')
    op.drop_table('organizations')
    op.drop_table('account')
    # ### end Alembic commands ###
