services:
  traefik:
    image: traefik:3.0
    ports:
      # Listen on port 80, default for HTTP, necessary to redirect to HTTPS
      - 80:80
    restart: always
    volumes:
      # Add Docker as a mounted volume, so that Traefik can read the labels of other services
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Mount the volume to store the certificates
    command:
        - --providers.docker
        - --providers.docker.exposedbydefault=false
        - --entrypoints.http.address=:80
        - --accesslog
        - --log
    networks:
        - traefik-public

networks:
    traefik-public:
        external: true