networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - api
    networks:
      - dev

  db:
    image: postgres:15
    container_name: vkadmin_db
    env_file:
      - .env-non-dev
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresdata:/var/lib/postgresql/data
    networks:
      - dev
      
  redis:
    image: redis:latest
    container_name: vkadmin_redis
    ports:
      - 6379:6379
    networks:
      - dev

  nats:
    image: 'nats:latest'
    ports:
      - "4222:4222"
    networks:
      - dev

  scheduler:
    build:
      context: .
    command: sh -c "taskiq scheduler app.tasks.vk_stat:scheduler"
    env_file:
      - .env-non-dev
    depends_on:
      - nats
    networks:
      - dev

  api:
    build:
      context: .
    container_name: vkadmin
    env_file:
      - .env-non-dev
    depends_on:
      - db
      - redis
      - nats
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    ports:
      - 7777:8000
    networks:
      - dev

  frontend:
    build:
      context: templates/
    container_name: vkadmin_frontend
    ports:
      - 5468:80
    depends_on:
      - api
    networks:
      - dev



volumes:
  postgresdata: