services:
  db:
    image: postgres:15
    container_name: vkadmin_db
    env_file:
      - .env-non-dev
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_LOG_STATEMENT: all
    volumes:
      - postgresdata:/var/lib/postgresql/data
    networks:
      - traefik-public

  nats:
    image: 'nats:latest'
    ports:
      - "4222:4222"
    networks:
      - traefik-public

  api:
    build:
      context: .
    container_name: vkadmin
    restart: always
    env_file:
      - .env-non-dev
    depends_on:
      - db
      - nats
    command: sh -c "alembic stamp fb7e68f8b917 && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    ports:
      - 7777:8000
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.services.api.loadbalancer.server.port=8000
      - traefik.http.routers.api-http.rule=Host(`${DOMAIN?Variable not set}`) && PathPrefix(`/api`)
      - traefik.http.routers.api-http.entrypoints=http
      - traefik.http.middlewares.api-stripprefix.stripprefix.prefixes=/api
      - traefik.http.routers.api-http.middlewares=api-stripprefix
      - traefik.http.routers.api-https.rule=Host(`${DOMAIN?Variable not set}`) && PathPrefix(`/api`)
      - traefik.http.routers.api-https.entrypoints=https
      - traefik.http.routers.api-https.tls=true
      - traefik.http.routers.api-https.tls.certresolver=le
      - traefik.http.routers.api-https.middlewares=api-stripprefix
    environment:
      - DOMAIN=${DOMAIN}
    networks:
      - traefik-public

  scheduler:
    build:
      context: .
    container_name: vkadmin-scheduler
    restart: always
    env_file:
      - .env-non-dev
    depends_on:
      - nats
      - api
    command: sh -c "taskiq scheduler app.tasks.vk_stat:scheduler"
    networks:
      - traefik-public

  frontend:
    build:
      context: ./templates
      args:
        VITE_API_URL: https://${DOMAIN?Variable not set}
        NODE_ENV: production
    container_name: vkadmin_frontend
    depends_on:
      - api
    env_file:
      - .env-non-dev
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
      - "traefik.http.routers.frontend-http.rule=Host(`${DOMAIN?Variable not set}`)"
      - "traefik.http.routers.frontend-http.entrypoints=http"
      - "traefik.http.routers.frontend-https.rule=Host(`${DOMAIN?Variable not set}`)"
      - "traefik.http.routers.frontend-https.entrypoints=https"
      - "traefik.http.routers.frontend-https.tls=true"
      - "traefik.http.routers.frontend-https.tls.certresolver=le"
    environment:
      - DOMAIN=${DOMAIN}
    networks:
      - traefik-public

  fail2ban:
    image: crazymax/fail2ban:latest
    container_name: fail2ban
    restart: always
    network_mode: host
    volumes:
      - ./fail2ban-config:/etc/fail2ban
      - postgreslogs:/var/log/postgresql:ro
      - /var/run/docker.sock:/var/run/docker.sock
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TZ=Europe/Moscow

networks:
  traefik-public:
    external: true 

volumes:
  traefik-certificates:
  postgresdata:
