FROM node:alpine as build

WORKDIR /templates

COPY package.json package.json
RUN npm install
COPY . .
RUN npm run build

# Используем http-сервер на базе Node.js
FROM node:alpine

WORKDIR /app

# Копируем скомпилированные файлы
COPY --from=build /app/dist .

# Устанавливаем простой HTTP-сервер для обслуживания файлов
RUN npm install -g http-server

EXPOSE 80

CMD ["http-server", "-p", "80"]